phases:
- phase: Windows_Unit_Tests
  queue:
    timeoutInMinutes: 90
    parallel: 4
    matrix:
      debug_32:
        _configuration: Debug
        _testKind: Test32
      debug_64:
        _configuration: Debug
        _testKind: Test64
      release_32:
        _configuration: Release
        _testKind: Test32
      release_64:
        _configuration: Release
        _testKind: Test64

  steps:
    - script: build/scripts/cibuild.cmd -$(_configuration) -testDesktop -$(_testKind)

    - task: PublishTestResults@1
      inputs:
        testRunner: XUnit
        testResultsFiles: '**/xUnitResults/*.xml'
        mergeTestResults: true
        testRunTitle: 'Unit Tests $(_configuration) $(_testKind)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\$(_configuration)\Logs'
        ArtifactName: 'Build Diagnostic Files $(_configuration) $(_testKind)' 
        publishLocation: Container
      continueOnError: true
      condition: failed()
           
- phase: Windows_Determinism_Test
  queue:
    timeoutInMinutes: 90
  steps:
    - script: build/scripts/cibuild.cmd -testDeterminism

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\Debug\Logs'
        ArtifactName: 'Build Determinism Files'
        publishLocation: Container
      continueOnError: true
      condition: failed()
